# Menggunakan image PHP dengan Apache
FROM php:8.1-apache

# Install ekstensi PHP yang dibutuhkan
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libzip-dev \
    unzip \
    git \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd zip

# Aktifkan mod_rewrite untuk Apache
RUN a2enmod rewrite

# Set working directory
WORKDIR /var/www/html

# Copy composer.lock dan composer.json untuk menginstall dependensi
COPY composer.lock composer.json ./

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install dependensi Laravel
RUN composer install --no-dev --optimize-autoloader

# Copy seluruh file aplikasi Laravel ke dalam container
COPY . .

# Set permission untuk folder storage dan bootstrap/cache
RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache

# Expose port 80
EXPOSE 80

# Command untuk menjalankan aplikasi
CMD ["apache2-foreground"]
